// NFL Teams List

module.exports = [
  "Salvatore Ferragamo",
  "Valentino",
  "Gucci",
  "Chanel",
  "Louis Vuitton",
  "Hermes",
  "Christian Louboutin",
  "Versace",
  "Prada",
  "Saint Laurent",
  "Jimmy Choo",
  "Christian Dior",
  "Dolce and Gabbana",
  "Burberry",
  "Balenciaga",
  "Miu Miu",
  "Fendi",
  "Armani",
  "Givenchy",
  "Stuart Weitzman",
  "Vera Wang",
  "Bottega Veneta",
  "Isaac Mizrahi",
  "Vince Camuto",
  "Kate Spade",
  "Marc Jacobs",
  "Rebecca Minkoff"
  ];
